In [8]:
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)
print(keras.__version__)

2.0.0-alpha0
2.2.4-tf


In [9]:
model = keras.Sequential()
model.add(keras.layers.Dense(32,activation='relu'))
model.add(keras.layers.Dense(32,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax'))

In [10]:
keras.layers.Dense(32,activation='relu')
keras.layers.Dense(32,activation=tf.sigmoid)
keras.layers.Dense(32,kernel_initializer='orthogonal')
keras.layers.Dense(32,kernel_initializer=keras.initializers.glorot_normal)
keras.layers.Dense(32,kernel_regularizer=keras.regularizers.l2(0.01))
keras.layers.Dense(32,kernel_regularizer=keras.regularizers.l1(0.01))

In [12]:
model = keras.Sequential()
model.add(keras.layers.Dense(32,activation='relu'))
model.add(keras.layers.Dense(32,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax'))
model.compile(optimizer = keras.optimizers.Adam(learning_rate=0.01),
             loss = keras.losses.categorical_crossentropy,
             metrics = [keras.metrics.categorical_accuracy])

In [13]:
import numpy as np

train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))

val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 0s 236us/sample - loss: 18.8256 - categorical_accuracy: 0.1170 - val_loss: 36.2292 - val_categorical_accuracy: 0.1250
Epoch 2/10
1000/1000 [==============================] - 0s 15us/sample - loss: 43.4061 - categorical_accuracy: 0.0970 - val_loss: 56.4080 - val_categorical_accuracy: 0.0850
Epoch 3/10
1000/1000 [==============================] - 0s 18us/sample - loss: 57.5594 - categorical_accuracy: 0.1170 - val_loss: 60.1083 - val_categorical_accuracy: 0.0900
Epoch 4/10
1000/1000 [==============================] - 0s 17us/sample - loss: 63.9593 - categorical_accuracy: 0.1090 - val_loss: 70.2916 - val_categorical_accuracy: 0.0900
Epoch 5/10
1000/1000 [==============================] - 0s 17us/sample - loss: 91.4462 - categorical_accuracy: 0.0870 - val_loss: 125.5907 - val_categorical_accuracy: 0.0950
Epoch 6/10
1000/1000 [==============================] - 0s 17us/sample - loss: 169.195

In [14]:
dataset = tf.data.Dataset.from_tensor_slices((train_x,train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x,val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset,epochs=10,steps_per_epoch=30,validation_data=val_dataset,validation_steps=3)

W0705 13:40:13.880118 19296 training_utils.py:1353] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
30/30 [==============================] - 0s 2ms/step - loss: 1191.1010 - categorical_accuracy: 0.1010 - val_loss: 1092.4255 - val_categorical_accuracy: 0.1250
Epoch 2/10
30/30 [==============================] - 0s 2ms/step - loss: 2250.8527 - categorical_accuracy: 0.0951 - val_loss: 3571.0033 - val_categorical_accuracy: 0.0938
Epoch 3/10
30/30 [==============================] - 0s 2ms/step - loss: 4554.5134 - categorical_accuracy: 0.0951 - val_loss: 5163.6891 - val_categorical_accuracy: 0.0938
Epoch 4/10
30/30 [==============================] - 0s 2ms/step - loss: 6411.1779 - categorical_accuracy: 0.1165 - val_loss: 6651.8206 - val_categorical_accuracy: 0.1146
Epoch 5/10
30/30 [==============================] - 0s 2ms/step - loss: 9775.8155 - categorical_accuracy: 0.0951 - val_loss: 8665.3395 - val_categorical_accuracy: 0.1250
Epoch 6/10
30/30 [==============================] - 0s 2ms/step - loss: 9634.4383 - categorical_accuracy: 0.1036 - val_loss: 12664.0872 - val_categori

In [17]:
test_x = np.random.random((1000,72))
test_y = np.random.random((1000,10))
model.evaluate(test_x,test_y,batch_size=32)

test_data = tf.data.Dataset.from_tensor_slices((test_x,test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data,steps=30)

result = model.predict(test_x,batch_size=32)
print(result)

30/30 [==============================] - 0s 1ms/step - loss: 25624.4336 - categorical_accuracy: 0.0927
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
